spring:
  application:
    name: itachallenge-document
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jmx:
    enabled: true

springdoc:
  swagger-ui:
    path: "/swagger"
    configUrl: /api-docs/swagger-config
    operationsSorted: method
    urls:
      - name: Auth OpenAPI Definition
        url: "http://localhost:8761/api-docs"
      - name: Challenge OpenAPI Definition
        url: "http://localhost:8762/api-docs"
      - name: User OpenAPI Definition
        url: "http://localhost:8764/api-docs"
      - name: Score OpenAPI Definition
        url: "http://localhost:8763/api-docs"
      - name: All OpenAPI Definition
        url: "http://localhost:8769/api-docs/all"
  api-docs:
    enable: true
    path: "/api-docs"
  cache:
    disabled: true

server:
  port: 8769

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

logging:
  level:
    root: INFO
    "[org.springframework]": ERROR
    "[com.businessassistantbcn]": INFO
  pattern:
    # console: Spring's default
    file: "%date %5level %-40.40logger{39} [%thread] %msg%n"
#  file:
#    name: itachallenge-challenge.log

url:
  connection_timeout: 30000
  maxBytesInMemory: 30000000

